### PR TITLE
add expire view count feature

### PR DESCRIPTION
**Pull request by 0APOCALYPSE0**
Feature - Add expiry view count
#46 

image

- [x] Add feature

### CODE REVIEW

**Comment by vinyashegde** [comment]
@0APOCALYPSE0 can you explain it briefly what do you want to do?

**Comment by 0APOCALYPSE0** [comment]
So according to this feature, shorten url will get expire after using few number of times. So for example during the creation of url if user provide 5 as a input in expiry count view input field then that shorten url can only be used for 5 Times only after that it will get expire.

**Comment by vinyashegde** [comment]
> @vinyashegde So according to this feature, shorten url will get expire after using few number of times. So for example during the creation of url if user provide 5 as a input in expiry count view input field then that shorten url can only be used for 5 Times only after that it will get expire. In short, now user can decide how many number of times url can be used. After the view/use limit is over then url will get expire. But if user want to generate a url with no expiry then he can leave that field as empty.
> 
> Reference: expire_at_views number optional Number of views the short url will be valid.
> 
> I have used expire_at_views property here API docs: https://t.ly/docs

@0APOCALYPSE0 i checked your pr it the feature isn't working

**Comment by 0APOCALYPSE0** [comment]
@vinyashegde it should work. I noticed one thing so suppose if you are passing n number then it will expire after n+1 example: pass 3 as a input and you can can use them link 4 times after 4 times it will expire. I don't know why api expire url after n+1 times instead of after n times

**Comment by vinyashegde** [comment]
@0APOCALYPSE0 can you make some small changes make a button to enable the view count input field and disable on hide it as optional

**Comment by 0APOCALYPSE0** [comment]
@vinyashegde added

off view count
image

on view count
image

**Comment by vinyashegde** [comment]
@0APOCALYPSE0  i checked your pr the toggle button was not working. I checked it on multiple browsers still its the same
Screenshot 2023-10-05 211346

Fix it!

**Comment by 0APOCALYPSE0** [comment]
@vinyashegde I have moved inline event to js now you will not get extension error
For me toggle button is working. here attaching the video:
ezgif com-video-to-gif


Can you tell me the steps how are you testing?

**Comment by vinyashegde** [comment]
@0APOCALYPSE0  amazing work🚀
and good luck for the hacktoberfest!!

**Pull request merged**
