### PR TITLE
Customized your privacyPolicy.md file

### PR DESCRIPTION
**Pull request by 1AmSammi3**
Hi 👋.
I took a look at your privacy policy file and I must say, it needed some work. 
I did a bit of customizing to make it more readable, while preserving it's contents.
Do have a look and merge if you like it.
Thanks.

### CODE REVIEW

**Comment by vinyashegde** [comment]
@1AmSammi3 The policy is wrong shorto is not a website it's an extension. Remake it properly after using this extension

**Comment by 1AmSammi3** [comment]
> @1AmSammi3 The policy is wrong shorto is not a website it's an extension. Remake it properly after using this extension

Ok.
Will fix that in a jiffy

**Comment by 1AmSammi3** [comment]
Fixed.
Please review.
Thanks alot

**Comment by vinyashegde** [comment]
@1AmSammi3 No, everything is still wrong we don't collect any information

Fix everything correctly then do a pr 
Also star this repo ⭐

**Comment by 1AmSammi3** [comment]
> @1AmSammi3 No, everything is still wrong we don't collect any information
> 
> Fix everything correctly then do a pr Also star this repo ⭐

Oh.
But all I did was edit this 
Screenshot_20231004-193436

I didn't add any other content other than what's on your main branch.

**Comment by vinyashegde** [comment]
@1AmSammi3 use the extension ones and remake it with correct information

**Comment by 1AmSammi3** [comment]
> @1AmSammi3 use the extension ones and remake it with correct information

Roger that

**Comment by vinyashegde** [comment]
@1AmSammi3 good work 🔥

**Comment by 1AmSammi3** [comment]
Thanks alot sir

**Pull request merged**
